/*
* This Java File was generated by Bootleg
* If you modify it you will probably lose changes!
*/
package org.openntf.xsp.bootlegged.config;

public class BootleggedConfigs {

	public static String[] concat(String[] s1, String[] s2) {

		String[] s = new String[s1.length + s2.length];
		System.arraycopy(s1, 0, s, 0, s1.length);
		System.arraycopy(s2, 0, s, s1.length, s2.length);
		return s;
	}

	public static String[] addXspConfigFiles(String[] files) {

		return concat(files, new String[] {
		});
	}
}
